### ISSUE TITLE
CLI for config operations

### ISSUE THREAD

**Issue by bswck** [bswck/configzen#24]
### Use case

[`config.yml`]
```yaml
foo:  # a comment
  bar: 5
  biz:
    baz: 10
```
```shell
> configzen foo.bar  # automatically detect it's about config.yml`
5
```
```shell
> configzen foo.bar=6  # set foo.bar to 6, preserve comments`
[config.yml] Set foo.bar to 6
```
